### ISSUE TITLE
chair selection is complex and open to abuse

### ISSUE THREAD

**Issue by npdoty** [patcg/patcg.github.io#1]
I don't think we need these complex charter rules about selecting new chairs. I would be happy to start with our initial chairs and note that if there's consensus among the chairs to add or replace, or a consensus among the group to change chairs, that we can do so. And if Aram and Sean go completely mad with power and ignore clear group consensus, we could ask the W3C Community Development Lead to step in. Elections of chairs (who judge consensus) might give the impression that if you elect your preferred chair, then that chair will evaluate consensus along similar lines (and if they don't, you can elect a different one).

If the group/chairs do want to keep the very specific appeal/election process in place, we should limit the ability to abuse it. Currently, as I read it, any five participants can cause the current chairs to step down for the duration of a five-week election process and repeat that indefinitely such that the group cannot make any progress at all. 

Chairs should not vacate their positions during an election process. Elections called for by participants should be limited to once a year.

**Comment by AramZS** [comment]
I am not super familiar with the W3C processes around chair election in general, and I think that there is flexibility in that CGs can generally make their own rules in that regard, but [I see a similar process set by our peers at Privacy CG](https://privacycg.github.io/charter.html#chair-selection) and I think it is reasonable to try and stay consistent with our peer groups in this regard. If there are other objections to this chunk of the charter I am willing to hear them, but I am not particularly inclined to make a change from a W3C-familiar process to a less standard one unless there are more folks who object. I think that if the process appears to be under abuse by participants we could call in the Community Development Lead from W3C in that case as well. 

That said, I hear your concern about the process being used to leave the group chair-less during the period leading up to and of the election and I note Privacy CG does not have that specific language, so that the group may maintain operations during the period of election. I think that might be worthwhile to change, but I would prefer to see that change proposed by a PR in this repo so that the process is clear and open to objections. I would prefer not to set a precedent of the chair(s) unilaterally changing the charter.

**Comment by martinthomson** [comment]
When writing/transcribing this, I considered the potential for a denial of service.  I concluded that there are a great many ways in which a bad actor might disrupt work so that another was not going to make this materially worse.  This might sound a little defeatist, but I prefer to think of that as being optimistic.  I don't think anyone here will act so maliciously.  Also, there are consequences outside of this process for what would be a very public act.

My sense is that - should an election be needed - the group is so badly dysfunctional that we might be better shutting down regular operation until the dysfunction is resolved.  I'd be OK with adding rules to that effect.

**Comment by npdoty** [comment]
I also tend to be optimistic, hence my preference for using consensus as the working mode rather than election of replacement chairs. But if we _are_ going to provide very precise rules, then it seems we shouldn't make rules such that it's trivial to slow or stop work. Nothing in these rules even says that you aren't supposed to call an election every time a chair does something you dislike, though I agree that seems like abuse of the intent.

We can follow the Privacy CG style (they are experimenting and it's worth trying out!), but to be clear, elections of chairs is _not_ the typical W3C Process, and doesn't apply to any Working Groups or Interest Groups, for example. In the W3C Process, voting is a last resort when consensus is impossible, or a way to handle non-substantive disagreements, and choosing chairs doesn't seem like either of those.

I can open a PR for either new-chairs-by-consensus or elections-don't-vacate-and-can't-be-repetitive, if there's preference among others for either of those.

**Comment by npdoty** [comment]
> I can open a PR for either new-chairs-by-consensus or elections-don't-vacate-and-can't-be-repetitive, if there's preference among others for either of those.

If anyone has a preference, I will create a PR.

**Comment by seanturner** [comment]
@npdoty the Privacy CG really ought to update to use 3797 :)

To be clear I will bow to the will of the group, here but you are suggesting either adopting the 2-step approach from [here](https://privacycg.github.io/charter.html#chair-selection) or striking the words ", then all current chairs must vacate their position" from [here](https://patcg.github.io/charter.html#chair-selection) and saying the same set of five community members can't bring an objection again.

**Comment by npdoty** [comment]
Sure, removing the vacate the position clause would help. I suggested just not having any more than one election per year. Changes in the set could help too, but given that any individual from any organization can join, I don't think that's much barrier to the repetition (ask your buddy to join representing themselves and call for an election).

My preference would just be that if the consensus of the group is that new chairs are needed, then we select new chairs by consensus and the old chairs step down at that time.

**Comment by martinthomson** [comment]
I might prefer not to defend against that sort of denial of service.  If we get to the point that the work of the group becomes untenable due to disagreements of that nature, we might as well say that the group has failed and move on with our lives.

Unlike, say, a national constitution, we don't need this charter to be perfect and robust in service of a body that needs to survive through just about anything.

**Comment by npdoty** [comment]
> Unlike, say, a national constitution, we don't need this charter to be perfect and robust in service of a body that needs to survive through just about anything.

My preference is also that this charter not be robust at that level of detail. For example, we could choose and change chairs by consensus. But if we are going to maintain detailed rules in the charter for vacating and electing chairs (which again, I think is unnecessary), I would prefer that there not be obvious ways to abuse them.

**Comment by martinthomson** [comment]
The reason that the charter doesn't currently select chairs by consensus is that chairs are necessary to adjudge consensus.  Hence the process that is, as you say, open to a trivial denial of service attack.

**Comment by seanturner** [comment]
TBH my normal reaction would be to suggest that this issue be closed because it does not look like there is really consensus to make a change. But, since this is related to selecting the chair and I am a chair, it is probably better to run some kind of consensus call on this.  @npdoty how about you generate a proposal for both the new-chairs-by-consensus and elections-don't-vacate-and-can't-be-repetitive. The chairs can then run the 1st ever patcg consensus call on 0) do nothing, 1) the new-chairs-by-consensus proposal, or 2) or elections-don't-vacate-and-can't-be-repetitive. This might be overkill, but option 0) is there if there are crickets to the call.

**Comment by seanturner** [comment]
@npdoty PTAL at the above suggestion. Would love to be able to close this one out.

**Comment by eriktaubeneck** [comment]
I would be supportive of option 2) "elections-don't-vacate-and-can't-be-repetitive", and don't see any particular downside to including it.

**Comment by npdoty** [comment]
Opened #9 and #10 (drafted as simple a change as I thought possible in each case, but welcome corrections).
